# Generated by Django 5.2 on 2025-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customeraccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='contact',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
